
dogmove:
  # Paths
  cleaned_data_path: "../data/DogMoveData_csv_format/DogMoveData_clean.csv"

  # Continual learning personalization

  # Sensors to use
  use_acc: true
  use_gyro: true
  sensor_locations: ["Back", "Neck"]

  # Behavior classes to include
  behaviors: ["Galloping", "Lying on chest", "Sitting", "Sniffing", "Standing", "Trotting", "Walking"]

  # Training
  num_pretrain_dogs: 2
  # cl_epochs : 5
  # batch_size:
  #   dog_train: 256
  #   dog_test: 512
  # replay_buffer_size: 10000
  # replay_batch: 128
  learning_rate: 0.001

dogmove_clean:
  raw_data_path: "../data/DogMoveData_csv_format/DogMoveData.csv"
  dog_info_path: "../data/DogMoveData_csv_format/DogInfo.xlsx"
  output_path: "../data/DogMoveData_csv_format/DogMoveData_clean.csv"
  # If set, only include these breeds (names must match DogInfo.xlsx). Leave empty to keep all.
  select_breeds: []
  # If set, only include these dog IDs. Leave empty to keep all.
  select_dog_ids: []


